name: update-history
run-name: fetching latest data
on:
  push:
  schedule:
    - cron: '2 10 * * 1-5'
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.5.1
      - name: Install project dependencies
        working-directory: ./scripts
        run: poetry install
      - name: Fetch the data
        working-directory: ./scripts
        run: poetry run ./fetch.py ../docs/history.json
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'ci: history updated'
